quarkus.quinoa.package-manager-install=false
quarkus.quinoa.ui-root-path=quinoa

%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:3000
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
$dev.quarkus.http.cors.headers=accept,authorization,content-type

%dev.quarkus.quinoa.dev-server.port=3000
